DATASET:
  NAME: "vg"
  MODE: "benchmark"
  PATH: "/media/2T/lizeng/caption/data/vg_bm/repo/scene-graph-TF-release/data_tools/DIOR"
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 1
MODEL:
  WEIGHT_IMG: "/media/2T/lizeng/caption/SGG/pretrained/faster_rcnn_ckpt.pth"
  WEIGHT_DET: ""
  ALGORITHM: "faster_rcnn"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
  ROI_RELATION_HEAD:
    NUM_CLASSES: 16
SOLVER:
  BASE_LR: 5e-3
  MAX_ITER: 100000
  STEPS: (70000,90000)
  CHECKPOINT_PERIOD: 5000
