DATASET:
  NAME: "vg"
  MODE: "benchmark"
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 1
MODEL:
  WEIGHT_IMG: "/media/2T/lizeng/caption/SGG/checkpoints/ObjectDetection/vg_benchmark_object/R-101-C4/sg_baseline_joint_0/BatchSize_2/Base_LR_0.005/checkpoint_final.pth"
  WEIGHT_DET: ""
  RELATION_ON: True
  ALGORITHM: "sg_baseline"
  USE_FREQ_PRIOR: False
  USE_RELPN: True
  BACKBONE:
    CONV_BODY: "R-101-C4"
    FREEZE_PARAMETER: True
  RPN:
    FREEZE_PARAMETER: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    DETECTIONS_PER_IMG: 64
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
    FREEZE_PARAMETER: True
  ROI_RELATION_HEAD:
    FILTER_NON_OVERLAP: False
    BATCH_SIZE_PER_IMAGE: 256
    TRIPLETS_PER_IMG: 100
    NUM_CLASSES: 16
    IMP_FEATURE_UPDATE_STEP: 2
    MSDN_FEATURE_UPDATE_STEP: 2
    GRCNN_FEATURE_UPDATE_STEP: 2
    GRCNN_SCORE_UPDATE_STEP: 2
SOLVER:
  BASE_LR: 5e-5
  MAX_ITER: 100000
  STEPS: (70000,90000)
  CHECKPOINT_PERIOD: 3000
